name: Lo que queramos (chihuahuas)


on:
  push:
    branches: [ "main" ]


jobs:
  platzi:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: ["18.x", "20.x", "22.x"]

      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm install -no-audit
      - run: npm run lint
      - run: npm run test
      - run: npm run build
